version: '3'

services:
  app:
    image: golang:1.9.2
    volumes:
      - .:/go/src/github.com/zaru/sample-struct:cached
    ports:
      - "1324:1324"
    tty: yes
    depends_on:
      - kvs
  kvs:
    image: redis
    ports:
      - "6379:6379"
volumes:
  data:
